Repository UCLA-Creative-Labs/sunshine, pull requests merged in 2020-11, with the labels that each got.

#55 feat: spreadsheet implementation for hook based cache
  .gitignore
  netlify.toml
  package.json
  scripts/create-dotenv.js
  scripts/pre-build.js
  src/assets/notifications.json
  src/assets/teamInfo.json
  src/components/App.tsx
  yarn.lock
Labels: feature

#59 fix: Minor bugfixes
  src/components/Section/ItemBlock.tsx
  src/components/Section/index.tsx
  src/components/Team/index.tsx
Labels: bug, chore

#58 feat: Accessibility changes
  src/components/Section/ItemBlock.tsx
  src/components/Section/index.tsx
  src/components/styles/Section.scss
  src/components/styles/Splash.scss
  src/components/styles/_variables.scss
Labels: chore, feature

#61 fix: fix error with checking types
  src/components/Team/index.tsx
Labels: bug

#62 fix: Requested copy changes to front page
  src/assets/sectionInfo.json
  src/components/App.tsx
  src/components/Section/index.tsx
  src/components/Splash/index.tsx
Labels: bug

#63 feat: join page
  src/assets/joinInfo.json
  src/assets/orange-thing.svg
  src/assets/pink-thing.svg
  src/assets/purple-thing.svg
  src/assets/sectionInfo.json
  src/components/App.tsx
  src/components/Join/index.tsx
  src/components/styles/Join.scss
Labels: feature

#64 feat: Add Discord invite (never expires) to footer
  src/components/Footer.tsx
  src/components/styles/Footer.scss
Labels: feature
