Repository UCLA-Creative-Labs/sunshine, pull requests merged in 2020-09, with the labels that each got.

#22 feat: create all website sections and requisite components
  .eslintrc.js
  .stylelintrc.json
  custom_typing/import-jpeg/import-jpeg.d.ts
  custom_typing/import-jpeg/import-jpg.d.ts
  custom_typing/import-svg/import-svg.d.ts
  netlify.toml
  package.json
  public/index.html
  src/assets/cl-logo.svg
  src/assets/fall.svg
  src/assets/placeholder.svg
  src/assets/sectionInfo.json
  src/assets/spring.svg
  src/assets/sun.svg
  src/assets/sunmoon-bg.svg
  src/assets/sunmoon-face.svg
  src/assets/what-we-do.svg
  src/assets/who-are-we.svg
  src/assets/winter.svg
  src/components/App.tsx
  src/components/Footer.tsx
  src/components/ItemBlock.tsx
  src/components/Navbar.tsx
  src/components/Section.tsx
  src/components/Splash/SunMoon.tsx
  src/components/Splash/index.tsx
  src/components/styles/Footer.scss
  src/components/styles/ItemBlock.scss
  src/components/styles/Navbar.scss
  src/components/styles/Splash.scss
  src/components/styles/_variables.scss
  src/global.scss
  tsconfig.json
  webpack.common.js
  webpack.prod.js
  yarn.lock
Labels: effort/medium, feature

#26 feat: dynamic splash screen
  src/assets/moon.svg
  src/assets/sun.svg
  src/components/App.tsx
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/components/Section.tsx
  src/components/Splash/SunMoon.tsx
  src/components/Splash/index.tsx
  src/components/styles/Navbar.scss
  src/components/styles/Splash.scss
  src/components/styles/_variables.scss
Labels: effort/small, feature

#27 feat: make website mobile-friendly
  public/index.html
  src/components/App.tsx
  src/components/Section.tsx
  src/components/Splash/SunMoon.tsx
  src/components/styles/App.scss
  src/components/styles/Footer.scss
  src/components/styles/ItemBlock.scss
  src/components/styles/Navbar.scss
  src/components/styles/Splash.scss
  src/components/styles/_variables.scss
  src/global.scss
Labels: effort/small, feature

#28 chore: clean up and reorganize code
  custom_typing/import-scss/import-scss.d.ts
  src/components/App.tsx
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/components/Section/ItemBlock.tsx
  src/components/Section/index.tsx
  src/components/Splash/SunMoon.tsx
  src/components/Splash/index.tsx
  src/components/styles/Section.scss
  src/global.scss
  tsconfig.json
Labels: chore

#29 chore: make website copy up to standards
  src/assets/design-fellow.svg
  src/assets/develop-fellow.svg
  src/assets/sectionInfo.json
  src/components/App.tsx
  src/components/Splash/index.tsx
  src/components/styles/Section.scss
Labels: chore

#31 fix: add links to splash page
  src/assets/sectionInfo.json
  src/components/App.tsx
  src/components/Section/ItemBlock.tsx
  src/components/Section/index.tsx
Labels: bug

#33 fix: fixing some design inconsistencies and adding some cute animations
  src/assets/design-fellow.svg
  src/assets/develop-fellow.svg
  src/components/Section/ItemBlock.tsx
  src/components/styles/Section.scss
Labels: bug

#36 fix: nighttime splash text color and item text spacing
  src/components/styles/Section.scss
  src/components/styles/Splash.scss
  src/components/styles/_variables.scss
Labels: bug

#35 feat: add favicon + metadata
  public/index.html
  src/assets/favicon.ico
Labels: feature
